[package]
name = "emigui-miniquad"
version = "0.1.0"
authors = ["Logachev Fedor <not.fl3@gmail.com >"]
edition = "2018"

[dependencies]
egui = { git = "https://github.com/emilk/egui.git" }

miniquad = "0.2"

